### ISSUE TITLE
Read Code Convention

### ISSUE THREAD

**Issue by nartoan** [nartoan/DesigningTheUserInterface#2]
Đọc các tutorial về chuẩn code, comment để làm việc với nhau dễ hơn
Tham khảo : 

- [Trên stdio.vn](http://www.stdio.vn/articles/read/22/stdio-coding-convention-level-1)
- [Trên http://tapchilaptrinh.vn/](http://tapchilaptrinh.vn/2012/07/25/coding-conventions-lat-mem-buoc-chat/)
- [Trên kipalog.com, theo phong cách kiếm hiệp](http://kipalog.com/posts/Luan-ve-comment-code--Phong-cach-kiem-hiep)
- [Code convention, Lưu tại DesigningTheUserInterface/docs ](https://github.com/nartoan/DesigningTheUserInterface/blob/master/docs/codeconventions.pdf)

**Comment by tieptv6669** [comment]
Thanks
