### ISSUE TITLE
Học dùng photoshop để cắt ghép tạo ra prototype cho web

### ISSUE THREAD

**Issue by nartoan** [nartoan/DesigningTheUserInterface#7]
[Tham Khảo](https://www.webdesign.org/how-to-create-a-clean-website-layout-in-photoshop.22287.html)

**Comment by nartoan** [comment]
Link này chi tiết hơn : [forum.vietdesigner.net](http://forum.vietdesigner.net/threads/tu-thiet-ke-mot-website-chuyen-nghiep-bang-photoshop-va-cach-ma-hoa.40111/)

**Comment by tieptv6669** [comment]
ok boss
